### ISSUE TITLE
Error in line 2392 in pysimplesql.py.

### ISSUE THREAD

**Issue by VeshchiyPolyak** [PySimpleSQL/pysimplesql#129]
Hello! 

I was trying using example from main page in section **Record Navigation** and get an error in line 20 in example code and error in pysimplesql.py in line 2392 label_text = query_info.split('.')[1].replace('fk', '').replace('_', ' ').capitalize() + ':'. 

So is there some easy solution for this or I myself do something wrong?

**Comment by PySimpleSQL** [comment]
Hello,

The readme is horribly out of date - sorry!  There have been so many changes going on that I've been waiting for them to be finalized so that I can go through and update the readme (it's going to be a fairly big job).

The examples folder is mostly up to date and should let you test the waters some while I try to get things caught up.

Also, we have been very actively working in the development branch and some things will be changing soon - you might want to actually work off of that branch, as that will be the path forward for the project.

I'm hoping to finish cleaning things up in the next couple of weeks, updating the readme and pushing v3.0 to pypi soon, so hopefully the pains are temporary for you

**Comment by ssweber** [comment]
Hi VeshchiyPolyak, you can grab the current development branch (and all the working examples) as a [zip-file](https://github.com/PySimpleSQL/pysimplesql/archive/refs/heads/development.zip).

**Comment by VeshchiyPolyak** [comment]
Thanks for help! I check it out and will try to use it in my project.
