### ISSUE TITLE
My 3.0 shortlist

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#137]
I know you’d like to wrap up this release. Here is my shortlist… totally OK if these don’t get in! Will also be testing to make sure we haven’t missed any bugs (need to get a MySQL/Postgres setup going to do same tests on those).

- [x] #79 
- [x] #136
- [x] Add edit-protectable sg.CalendarButton example to journal internal 
- [x] #89 - Was the foreign key toggle work-around good enough for now? ( for deleting a parent that cascades down to a grandchild deletes).
- [x] #176 Get cascade delete foreign key from database. Ready to add in once the current pull requests land and decision on what to call current cascaded relationships

**Comment by PySimpleSQL** [comment]
Yeah, I would like to see the LanguagePack stuff make it in. Supporting
Text as a field would be very easy too.

The calendar button is a good idea. The glue code to edit protect it should
be on the user side in the example, so that should be pretty straight
forward.

As far as the foreign key deleting, the proper way to do it is by looking
at how it is configured in the database and acting accordingly (ON DELETE
CASCADE), as it should be up to the schema of the database to decide how to
do it.  The workaround for now is fine, and may even have to stay for the
parenting behavior aspect of it.  If I get a decent chunk of time soon I
may wrap that in before the update, but if not l just add it in with an
update later down the road.

After 3.0 goes out, I would like to look at:
- going through and seeing what additional PySimpleGUI elements still need
supported and getting them wrapped in
- ON DELETE CASCADE if not done before that
- A good example program that really shows off how to use pysimplesql in a
real world program.  I think I've decided on a cash register application
that has separate front end (cash register app) and a secondary
configuration app where products, barcodes, coupons, users, etc can be
managed.  Hooking up a cheap USB scanner and thermal receipt printer to a
raspberry pi and chosing a fun theme would make it a very fun play cash
register for children.
- adding support for more databases, including excel files

After that when things stabilize, I have some related libraries that I
would like to release.  I made a pretty awesome printing module that would
need cleaned up and generalized  (Linux only, possibly Mac too for the most
part- would need Windows equivalents added).  I also have a start on a
report generating library that operates like PySimpleGUI for generating
reports by list of list layouts, which also would need generalized and
cleaned up.

Assuming PySimplePrinter, PySimpleReport,  PySimpleGUI and pysimplesql are
all available, then you have a nice full replacement for MS Access

**Comment by ssweber** [comment]
Cool! That'll def help testing.

For templating, for a work project I have used [docxtpl](https://pypi.org/project/docxtpl/), which allows you to put jinja templates in a word docx and [dataset](https://dataset.readthedocs.io/en/latest/index.html) for the database calls, but I'd like to see how you approach it!

**Comment by PySimpleSQL** [comment]
Shoot me an email when you get a chance.
***@***.***
