### ISSUE TITLE
New Settings or Behavior class for form/dataset init variables

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#211]
Instead of overloading the Form init with a ton of arguments, I'm thinking that we should have a Settings or Behavior for all the different settings. Then we can have one set_settings, or set_behavior, that acts like the themepack/languagepack.

app_behavior = Behavior('prompt_save' : ss.AUTOSAVE_MODE,  "save_quiet"=True}
frm = ss.Form(driver, bind_window=window, behavior=app_behavior}

or after its already init:

frm.set_behavior(app_behavior)

List would be:
prompt_save
save_quiet
update_cascade
delete_cascade
confirm_duplicate
duplicate_children
confirm_delete
force_save

**Comment by PySimpleSQL** [comment]
Yeah, I've thought about this too a few times.  I've been kind of torn,
only because I was trying to provide an interface that is somewhat similar
to PySimpleGUI, since it's a prerequisite for the whole project.  I'm not a
huge fan of huge init parameter sets either.

A work around I often use is to define a dict of the parameters and dump
them into the init with ** like with the connection parameters for the
remote databases.  Maybe this would be the cleanest approach for examples
that make the init function overly large?

**Comment by ssweber** [comment]
I’ll take a look at how you do it with the connections param, when I get around to the confirm_delete, confirm_duplicate

**Comment by ssweber** [comment]
I’ll just add to the init section for now then. You’re right, pysimplegui doesn’t shy away from a ton of args!
