### ISSUE TITLE
How do you run examples from their folder?

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#250]
This is probably a dumb question.

What is your setup that allows you to run examples using the checked out GitHub repository pysimplesql?

I’ve just been copy-pasting examples into the root directory, 😅. To ` import pysimplesql as ss`

**Comment by PySimpleSQL** [comment]
There's a ton of other benefits too:
- I can install multiple python versions in isolated environments and specify the version to use when I launch
- Each project is in its own virtual environment, so and pip packages I need to install are specific to that project only - I don't have to litter my machine with dependencies for all of these different projects
- I can set up local repositories and link them to other projects.  For example, all of my current projects outside of PySimpleSQL get the package locally instead of from PIP.  That way, as long as I checkout the development branch of pysimplesql and the development branch of some other project, that project will use the development version of pysimplesql
- Theres tons and tons of plugins to integrate everything from Ruff, Black, Docker, you name it - they you can manage everything from one place
- All of the git actions are handled right from the PyCharm IDE.  Commits, checkouts, pull requests, pushes, pulls are all super easy right in the IDE.  Even reviews and merges, all without even having to leave the IDE

**Comment by ssweber** [comment]
Thanks. I have it installed, I’ll start getting familiar with it :)
