### ISSUE TITLE
Revert default order_clause to pk?

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#296]
What do you think of reverting default order_clause to pk? It is description_column currently.

I believe it changed when table-sorting or virtual records were added, and I find it a little surprising to have the default behavior resorting new entries alphabetically.

**Comment by PySimpleSQL** [comment]
Yeah, I guess it depends on the type of application.  Description makes
sense for records containing names, addresses or similar data that a user
would expect to be sorted.  Maybe this should be a parameter to bind()?
The default doesn't matter to me really, as in either case it caters to one
group or the other, since it's so dependent on the type of data

**Comment by ssweber** [comment]
good point. we'll add to the init parameters.
