### ISSUE TITLE
How to add 'prompt_save' to all my queries?

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#32]
In the query class, you have prompt_save set to False. I can modify this directly.

How could I modify this on this on a global basis or auto-added table basis?

eg "def set_prompt_save(True)

**Comment by PySimpleSQL** [comment]
My plan is to work on the prompt to save code on Monday.  I disabled it byy
default because it isn't fully working in all situations yet.  I will be
sure to add a global promt_save to the parent form to handle this on a
global basis

**Comment by ssweber** [comment]
I noticed that once I started playing with it😄 .

That would be amazing if you got it fully working! I’ll try to post a stripped down version of my use-case before Monday. I’m using tabs, so they are in a TabGroup.

For prompt_save, I think it’d be nice to mimic Dbbrowser. When you first change to a table/record, the save button is greyed out. If a change is made, it becomes active. Once you save, no message is displayed, but the save button greys out again.

I honestly didn’t get far enough studying to understand how pysimplesql triggers prompt_save on a table row/selector change…  did find https://github.com/PySimpleGUI/PySimpleGUI/issues/1259 (bottom reply), where Mike is explaining how to only grab values from the active tab…

**Comment by PySimpleSQL** [comment]
Working from memory, it wasn't very optimized or conplicated.  It basically
compared every PySimpleGUI control to the currently selected query record,
column by column regardless of visibility on the screen.  I will check my
notes when I get home on Monday, but I think it was an easy fix to get it
working again.  I'll look at ways to add the save button enable/disable
functionality, maybe even a simple call back would be fine for this.

Again, I appreciate the flow of excellent ideas you're providing.  When I
get a chance l will have to share some of the projects I use this on
myself.  Your ideas will definitely help improve my own projects (one of
which I plan on commercializing possibly this year)

**Comment by PySimpleSQL** [comment]
I did a couple of commits that should fix this issue.  I documented the changes (and why) in both the comments and the commits.  If you could, can you test these and leave your thoughts and comments?  After we get some good testing in, I'll finish things up and release the update.

A quick summary:
- The prompt_save() method is recursive, so a parent=<bool> parameter was added so that code that actually prompted only ran at the 1st recursion level
- added a prompt_save parameter to the first(), next() etc.. record selection methods so that prompt_save could manually be skipped for situations that warrant it (for example, on a requery the first record is selected - this is a case where we don't want to prompt save when a record changes - so this call was changed to first(prompt_save=False) for example. (See the commit message for a little more detail, as I'm not 100% sure that I like the parameter name).  In any case, just looking for some feedback and see how it does in your use case.
Thanks!

**Comment by PySimpleSQL** [comment]
Just did another push that fixes the issues I had with my first attempt above.  I think this is much better now

**Comment by PySimpleSQL** [comment]
And another push that uses the new records_changed() function to dynamically enable/disable the save button, per earlier conversations.

**Comment by ssweber** [comment]
Thanks for the example! I'll consider this closed
