### ISSUE TITLE
Add value/column : function map

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#56]
The journal_with_data_manipulation.py doesn't work with query prompt_save because the element_value != the table_value.

We'll need to make some kind of value_map or column_map (don't know which term you like using more, you use 'for c in self.frm.element_map:' and 'for v in self.frm.element_map:') that can be hooked into into records_changed...
```
def cb_date_encode{
convert to unix timestamp
}
value_map = {'date_record_key':, cb_date_encode()}
```
then at top of update_elements:
```
if c['key'] in self.frm.value_map.keys():
   custom_function = self.frm.value_map[c['key']]
   element_val = custom_function(c['element'].get())
```

_Originally posted by @ssweber in https://github.com/PySimpleSQL/pysimplesql/issues/54#issuecomment-1425993138_

**Comment by PySimpleSQL** [comment]
I've been experimenting with this.  Here is the plan to make this better:
- Keep the callback system in place as is, (but don't use it for data manipulation, unless of course you want to)
- Make a new transform that can be set for any query column.  The plan is to use one transform callback function that takes a parameter to either encode or decode the data
- Data conversion happens when either reading from or writing to the database.  In this way, once the conversion is set, everything just automatically works without the need for anything complicated, and without future updates having to worry about it

**Comment by PySimpleSQL** [comment]
The new Query transforms handle this pretty well now - so for now we will call this one good.  Individual sg elements can already have a callback as well for special case updating, so I think we have most bases covered
