### ISSUE TITLE
Database abstraction / using an ORM

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#74]
I was thinking about this the other day. What are you thoughts on using an ORM like Pony to handle the backend?

This is all new to me, but I imagine first switch to using their execute() function, and then work through replacing functionality with their higher level functions. 

————————————————————
My next big update will be some database abstraction so that I can start
adding other database engines :)

_Originally posted by @PySimpleSQL in https://github.com/PySimpleSQL/pysimplesql/issues/70#issuecomment-1432424213_

**Comment by ssweber** [comment]
Hah - posted this, then saw you already created an abstracted_database branch with a ton of changes. :)

**Comment by PySimpleSQL** [comment]
Yeah, it was quick and dirty but time was pretty tight this week.  I
actually did everything during slow times at work on a raspberry pi.  I'll
clean it up when i have the luxury to sit at my workstation for a bit.

I did consider an ORM, but this project is pretty lightweight and I didn't
want to bloat it too much- plus the specialized cases of getting table
names, column names and relationships is probably outside the scope of most
ORMs anyway.  I enjoy abstracted coding and thought it would be a little
more fun regardless.

Adding MySql and Postge will be quite easy now, so this will be a huge leap
in capability

**Comment by ssweber** [comment]
BTW - I tested the sqlite version of your abstracted_database on my work program, and it looks like everything was working.

**Comment by PySimpleSQL** [comment]
Awesome, thanks

MySql driver is now working!  It wasn't as bad as I thought it would be to
implement.  Here is a test script if you want to test it out:

> import pysimplesql as ss
> driver = ss.Mysql('sql9.freesqldatabase.com','sql9598795','DMmCAFX2es','sql9598795')
>
> tables = driver.table_names()
> for t in tables:
>     print(f'Table: {t}')
>     columns = driver.column_names(t)
>     print(f'\tColumns: {columns}')
>     pk_col = driver.pk_column(t)
>     print(f'\tPrimary key: {pk_col}')
>
> print('Relationships: ')
> relationships=driver.relationships()
> print(f'\t{relationships}')
>
> print(f'Test Query:')
> q = 'SELECT * FROM Contact;'
> rows = driver.execute(q)
> print(f'\t{rows}')
>
>

**Comment by PySimpleSQL** [comment]
Postgres driver is (mostly) working.  I just need to get a couple of
example working now.  This code executes and returns expected results:
(assuming you've pip installed psycopg2 or psygcop2-binary)

> import pysimplesql as ss
>
> elephant_postgres = {
>     'host':'queenie.db.elephantsql.com',
>     'user':'yunaahtj',
>     'password':'OMX8u8CDKNVTrldLbnBFsUjxkArTg4Wj',
>     'database':'yunaahtj'
> }
> driver = ss.Postgres(**elephant_postgres)
> tables = driver.table_names()
> for t in tables:
>     print(f'Table: {t}')
>     columns = driver.column_names(t)
>     print(f'\tColumns: {columns}')
>     pk_col = driver.pk_column(t)
>     print(f'\tPrimary key: {pk_col}')
>
>
> print('Relationships: ')
> relationships=driver.relationships()
> print(f'\t{relationships}')
>
> print(f'Test Query:')
> q = 'SELECT * FROM Journal;'
> rows = driver.execute(q)
> print(f'\t{rows}')
>
>

**Comment by PySimpleSQL** [comment]
With most of the database abstraction done (duplicate still needs done), I wanted to have some discussion on some sane default behavior.  Currently, after inserting a new record:

- If the user navigates to a new record or creates another new record, they will be prompted to save. On a "No" selection, the virtual record is purged.
Is this a good default behavior, or should the record remain and marked as virtual?

- I think I may turn the SAVE_* constants to bitmasks so that I can add a flag to show the generic messsage.  This would be to prevent back to back messages, such as is the case currently when a query fails; The user is shown the query error message, then after that message the more generic message about problems encountered during saving.

- Regarding the marking of virtual records on Table selectors - should this be a user-definable option?  I kind of like the current implementation, though it's accomplished in a rather sneaky way by inserting an extra column in the table - which could lead to some confusion if a user had to do some low-level stuff with the table rows.  Maybe it's just a documentation issue?

**Comment by ssweber** [comment]
1) If there is a requery/requery_dependents, that virtual row would be lost, correct? If so, then yes, if user navigates away and says No to saving the virtual row, I think it should purged.
2) cool!
3) I like how you put in the star indicator. I think it’s good for now, unless you want to put a toggle to disable it, ie virtual_record_indicator = False .

**Comment by PySimpleSQL** [comment]
Thanks for the feedback - this is what I was thinking as well but its always nice to get opinions for others that use it

**Comment by ssweber** [comment]
For duplicate, is this all that would be needed to make it compatible with all three?

https://github.com/PySimpleSQL/pysimplesql/pull/77/commits/4dacca806a6d3f3ad2eaf3c29a0e12bcb274a601

**Comment by PySimpleSQL** [comment]
Not quite - we will probably have to add a duplicate method to the drivers themselves - Posgres in particular must have the table names in double quotes.  Plus, this will keep all direct queries inside the drivers

**Comment by PySimpleSQL** [comment]
Huge improvements to this today.  Should fix a ton of little collision issues
- The SQLDriver abstract class got quite a bit of improvements to reduce the amount of work required to write a new driver
- Got rid of the UPSERT in favor of separate INSERT and UPDATE methods.  Additionally, these now return a ResultSet object, so inserted keys can be communicated back to the caller and the selector updated after the insert/update
- SQLite and MySQL use autoincrement to avoid collisions. PostgreSQL used nextval() to reserve a primary key, which is then manually inserted back into the database.  This also avoids collisions
- Due to the weirdness of PostgreSQL and sequences, made an option (default True) to sync the sequences in the database with the max primary key.  This should eliminate collisions from manual insertions outside of pysimplesql
-

Initial tests are very  promising.  I'd be interested in hearing how your parent/child tests go with this @ssweber

**Comment by ssweber** [comment]
I saw your flurry of activity. I tried testing, but ran into this bug:

https://user-images.githubusercontent.com/57631333/220761210-65ea5f7e-ee7b-4504-b608-ea7e50a1ca67.mp4

**Comment by ssweber** [comment]
The file I used for that is: [here](https://github.com/ssweber/pysimplesql-examples/blob/main/tests/parent%20child%20grandchild.py).

I tested with abstracted_database branch, current after your changes.

I also worked to unify the saving mechanism... Form.save_records, Form.prompt_save and Query.prompt_save all use Form.save_records in this diff: https://github.com/PySimpleSQL/pysimplesql/compare/abstracted_database...ssweber:pysimplesql:ab_save_record?diff=unified

Once we fix the above bug, I'll re-integrate this code, since it's not a clean merge.

**Comment by PySimpleSQL** [comment]
Great, thanks.  I probably won't get a chance to look at it until tomorrow,
but the example will help a lot

**Comment by ssweber** [comment]
Btw - I branched from [This branch](https://github.com/PySimpleSQL/pysimplesql/commit/4c7d9c20eb9d95652edd9ce84407c4252b9dea3c), so it’s just been in the commits from today. If that helps narrow it down. Might take a look at it later and narrow it down to the commit that introduces it.

**Comment by PySimpleSQL** [comment]
I did a quick attempt at a fix from my phone.   I'm not able to test myself, we have some differences still (my Form no longer supports sql_commands, as it's moved to the driver)

I'll look more tomorrow when I have a computer in front of me

**Comment by ssweber** [comment]
Cool I’ll test in the morning.

I posted the wrong form - this one uses the sqldriver.

https://github.com/ssweber/pysimplesql-examples/blob/abstract_database/tests/parent%20child%20grandchild.py

**Comment by PySimpleSQL** [comment]
Ok, I have the issue narrowed down.  For some reason, cursor.lastrowid is always returning 2 in the driver.  Going to look at it now.

**Comment by PySimpleSQL** [comment]
Just commenting with my research so far:
sqlite documentation states that cursor.lastrowid will return the the primary key from the the affected row on an INSERT or REPLACE query only, and None in all other instances. However, i'm showing that it returns 2 instead of None in other instances, and that is the issue we are having.  Going to continue researching to find a real fix before hacking around the issue

**Comment by PySimpleSQL** [comment]
Ok, fix is pushed.

In the end, I did have to kind of hack around the issue.  With SQLite, the cursor.lastrowid is not operating as it should per documentation.  After countless tests, not once could I get it to return None on an UPDATE query - which the docs clearly state should happen.

In the end, for SQLDriver.save_record() I just manually set the ResultSet.lastrowid = None, as in the end it really doesn't matter.  The caller already knows the pk, as it was passed into save_records() - so this will be more of a documentation issue that ResultSet.lastrowid will only be set when SQLDriver.insert_record() is run, or on any INSERT query executed with SQLDriver.execute().  This will at least be consistent across the databases on the pysimplesql end

**Comment by ssweber** [comment]
Your fix worked :). Thank you!

Maybe you were bumping into where pythons wrapper diverges from direct SQLite?

```
lastrowid:
Read-only attribute that provides the row id of the last inserted row. It is only updated after successful INSERT or REPLACE statements…
…if the insertion failed, the value of lastrowid is left unchanged. The initial value of lastrowid is None.
```
https://docs.python.org/3/library/sqlite3.html

**Comment by PySimpleSQL** [comment]
This is working quite well as a concept - I'm going to close this now
