### ISSUE TITLE
fk_changed in Query.save_record() firing when not needed

### ISSUE THREAD

**Issue by PySimpleSQL** [PySimpleSQL/pysimplesql#80]
I'm noticing the block of code that checks for fk_changes is setting fk_changed to True is returning True when it doesn't need to.

In the journal_internal.py example, you'll see that a SELECT query runs twice when inserting a new record, and then saving it.  Debugging I can see the first time the query runs is because fk_changed is True (the 2nd time it runs is because self.row.virtual is true) even though there was no fk_change in this instance

**Comment by ssweber** [comment]
I commented that I think that was my bad.
see this closed pull request: https://github.com/PySimpleSQL/pysimplesql/pull/76

I’ll do a pull to take out that functionality for now… because now I think that it deserves to be an an example using before_save, after_save instead.

see https://github.com/PySimpleSQL/pysimplesql/pull/78

**Comment by PySimpleSQL** [comment]
I actually don't mind it if you want to leave it in there, it's just not
quite working correctly yet is all

**Comment by ssweber** [comment]
this should be fixed now
