### ISSUE TITLE
Rename update_elements = True to update=True in save_record

### ISSUE THREAD

**Issue by ssweber** [PySimpleSQL/pysimplesql#83]
`def save_record(self, display_message=True, update_elements=True) -> None:`

Everywhere else you we use update=True to mean update_elements. Would this be a good time to rename it to update=True?

**Comment by PySimpleSQL** [comment]
I wad thinking we should rename all the updates to update_elements.  It's
more work, but more descriptive!

**Comment by ssweber** [comment]
Good idea

**Comment by ssweber** [comment]
What about dependents=True? to requery_dependents=True?

**Comment by PySimpleSQL** [comment]
I think we should use update_elements anywhere where we call
Form.update_elements()

Regarding requery_dependents, I'm kind of torn.  I've been starting to use
update_cascade when referring to relationships, because that's the actual
database term.  I also like requery_dependents though because I think it
makes more sense (for parameter names that don't directly deal with
relationships anyways).  So I'm thinking if a method triggers the reaquery
of a dependent table we should use requery_dependents

**Comment by ssweber** [comment]
One more:
Records_changed is a query function. But by default it returns True if any of its dependents are dirty.

I’d vote to make that recursive=False by default, and then id switch all the calls around.

and if you’d like to rename it something other than recursive… check_dependents/cascade?
